name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
            }
          enable-AzPSSession: false

      - name: Validate Bicep file
        run: |
          az bicep build --file infra/main.bicep
          az deployment sub validate \            
            --template-file infra/main.bicep \
            --parameters @infra/parameters_dev.json

      - name: What-If Deployment
        run: |
          az deployment sub what-if \
            --template-file infra/main.bicep \
            --parameters @infra/parameters_dev.json

      - name: Wait for approval
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: manual-approval-required

      - name: Deploy Bicep file
        id: deploy
        run: |
          az deployment sub create \
            --template-file infra/main.bicep \
            --parameters @infra/parameters_dev.json \
            --output json > deployment_output_dev.json

      - name: Print deployment outputs
        run: |
          cat deployment_output_dev.json
